language: java
jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f src/main/docker/Dockerfile -t andreformento/neighborhood-api:$COMMIT .
  - docker tag andreformento/neighborhood-api:$COMMIT andreformento/neighborhood-api:$TAG
  - docker push andreformento/neighborhood-api

#https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
